#!/bin/bash

help(){
    echo -e "Converts pictures from a given folder into"
    echo -e "html code for the gallery page. Assumes you have"
    echo -e "an images/large and image/small folder.\n"
    echo "Usage:"
    echo "gallery-gen <dir name>"
    exit 1
}

if [ $# -ne 1 ]; then
    echo "you give no directory! no code for you!"
    help
elif [ ! -d $1 ]; then
    echo "your directory no exist! no code for you!"
    help
fi

LARGE_PICS="$1"

if [ "${LARGE_PICS: -1:1}" != "/" ]; then
    FILES="$LARGE_PICS/*"
else
    FILES="$LARGE_PICS*"
fi

GALLERY="<ul id=\"carousel\" class=\"elastislide-list\">"

for file in $FILES; do
    f=`basename $file`
    GALLERY="$GALLERY\n<li data-preview=\"images/large/$f\"><a href=\"#\"><img src=\"images/small/$f\" alt=\"$f\" /></a></li>\""
done

GALLERY="$GALLERY\n</ul>"
touch gallery-new.html
echo -e $GALLERY >> gallery-new.html


