#!/bin/bash

help(){
    echo -e "Converts pictures from a given folder into"
    echo -e "html code and appropriately sized pictues for"
    echo -e "the gallery page.\n"
    echo "Usage:"
    echo "gallery-gen <dir name>"
    exit 1
}

if [[ `bash ./gallery-gen-html $1` ]]; then
    help
fi

if [[ `bash ./gallery-gen-pics $1` ]]; then
    help
fi
